name: khalti_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  dio_smart_retry: ^5.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  get_it: ^7.6.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  pigeon: ^11.0.1

flutter:
  uses-material-design: true
