// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DeviceIdentifierDataApi {
  func getDeviceModel() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DeviceIdentifierDataApiSetup {
  /// The codec used by DeviceIdentifierDataApi.
  /// Sets up an instance of `DeviceIdentifierDataApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DeviceIdentifierDataApi?) {
    let getDeviceModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.khalti_task.DeviceIdentifierDataApi.getDeviceModel", binaryMessenger: binaryMessenger)
    if let api = api {
      getDeviceModelChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getDeviceModel()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getDeviceModelChannel.setMessageHandler(nil)
    }
  }
}
