// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by PGNDeviceIdentifierDataApi.
NSObject<FlutterMessageCodec> *PGNDeviceIdentifierDataApiGetCodec(void);

@protocol PGNDeviceIdentifierDataApi
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getDeviceModelWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void PGNDeviceIdentifierDataApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<PGNDeviceIdentifierDataApi> *_Nullable api);

NS_ASSUME_NONNULL_END
